Ubuntu.yml: upgrade "install-qt-action"
jaredtao/HelloActions-Qt pull request #7
Opened 2021-02-28 10:46 UTC by justin-himself

"jurplel/install-qt-action" needs to be upgraded to latest 2.13.0, current is 2.10.0.
Otherwise, when doing the action it would throw an error and fail to build.

```bash
python3 -m aqt install 5.12.10 linux desktop -O /home/runner/work/counselor/Qt
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 170, in __getitem__
    return next(iter(self.select(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/lib/python3.6/site-packages/aqt/__main__.py", line 28, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.6/site-packages/aqt/__init__.py", line 38, in main
    return cli.run()
  File "/home/runner/.local/lib/python3.6/site-packages/aqt/cli.py", line 352, in run
    return args.func(args)
  File "/home/runner/.local/lib/python3.6/site-packages/aqt/cli.py", line 142, in run_install
    self._run_common_part(output_dir, mirror)
  File "/home/runner/.local/lib/python3.6/site-packages/aqt/cli.py", line 123, in _run_common_part
    self.show_aqt_version()
  File "/home/runner/.local/lib/python3.6/site-packages/aqt/cli.py", line 245, in show_aqt_version
    module_name = dist.entry_points[0].name
  File "/home/runner/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 172, in __getitem__
    raise KeyError(name)
KeyError: 0
Error: The process 'python3' failed with exit code 1
```

2021-02-28 15:03 UTC, pzhlkj6612 requested changes

2021-02-28 15:03 UTC, pzhlkj6612 commented on .github/workflows/macos.yml
> +          path: bin/release/${env:targetName}.app
你好。这两处修改有问题，导致 [Build (macos-10.15, 5.12.10, clang_64) | 1997800253](https://github.com/jaredtao/HelloActions-Qt/pull/7/checks?check_run_id=1997800253) 在“ Package ”这一步出错：

1. 默认情况下， macOS 使用的 shell 是 bash 而不是 powershell 或 pwsh （ [Workflow syntax for GitHub Actions - GitHub Docs § Using a specific shell](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell) ）。在 powershell 和 pwsh 以外的、 GitHub Actions 使用的 shell 中并没有 `${env:foo}` 这种语法；
2. 看上去你是想用 GHA YAML 的上下文语法，那么应该是 `${{ env.targetName }}` （ [Context and expression syntax for GitHub Actions - GitHub Docs § `env` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context) ）；
3. 实际上，做这个修改是没有必要的，因为在 job 这一级设置的环境变量会应用到所有的 step ，所以直接使用 `${foo}` 就可以获取到对应的环境变量。

2021-03-01 01:06 UTC, jaredtao commented
I have upgrade all yml files to "jurplel/install-qt-action@v2.13.0"

2021-03-01 01:54 UTC, closed without merging

2021-03-01 02:48 UTC, pzhlkj6612 reviewed
My bad, you guys can ignore what I said before. 🤦‍♂️

2021-03-01 02:48 UTC, pzhlkj6612 commented on .github/workflows/macos.yml
> +          macdeployqt bin/release/${env:targetName}.app -qmldir=. -verbose=1 -dmg
By default, macOS uses bash as its shell, not powershell or pwsh ([Workflow syntax for GitHub Actions - GitHub Docs § Using a specific shell](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell)). In shells used by GitHub Actions other than powershell and pwsh, there is no such syntax as `${env:foo}` .

2021-03-01 02:48 UTC, pzhlkj6612 commented on .github/workflows/macos.yml
> +          path: bin/release/${env:targetName}.app
You should use `${{ env.targetName }}` to match the GHA YAML syntax ([Context and expression syntax for GitHub Actions - GitHub Docs § `env` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context)).

2021-03-01 02:48 UTC, pzhlkj6612 commented on .github/workflows/macos.yml
> +          path: bin/release/${env:targetName}.app
Sorry, I didn't get your intention and mixed these two changes. The first change matches No.1, and the second change matches No.2 .

I've rewritten the review.

2021-03-03 15:38 UTC, justin-himself commented on .github/workflows/macos.yml
> +          path: bin/release/${env:targetName}.app
My bad... that's just me messing around with the macos.yml, I didn't really expected the changes to be taken place here... 😂

Thanks for pointing out!

2021-03-04 04:32 UTC, pzhlkj6612 commented on .github/workflows/macos.yml
> +          path: bin/release/${env:targetName}.app
It's alright. :)

And, in the future, you can make new changes on a separate branch to prevent the auto sync.